basePath: /api/
definitions:
  config.Config:
    properties:
      defaultLimit:
        type: string
      defaultOffset:
        type: string
      environment:
        description: debug, test, release
        type: string
      httpport:
        type: string
      httpscheme:
        type: string
      influxBucket:
        type: string
      influxDatabase:
        type: string
      influxOrg:
        type: string
      influxToken:
        type: string
      influxURL:
        type: string
      passcodeLength:
        type: integer
      passcodePool:
        type: string
      secretKey:
        type: string
      serviceHost:
        type: string
      serviceName:
        type: string
      smtpfrom:
        type: string
      smtphost:
        description: Email Configuration
        type: string
      smtppassword:
        type: string
      smtpport:
        type: integer
      smtpusername:
        type: string
      version:
        type: string
    type: object
  github_com_Ramazon1227_BeatSync_api_http.Response:
    properties:
      data: {}
      description:
        type: string
      status:
        type: string
    type: object
  models.HRVAnalysisResult:
    properties:
      analysis_id:
        description: Unique identifier for the analysis
        type: string
      analysis_time:
        description: Timestamp of when the analysis was performed
        type: string
      hf:
        type: number
      lf:
        type: number
      lf_hf_ratio:
        type: number
      nn50:
        type: integer
      pnn50:
        type: number
      rmssd:
        type: number
      sd1:
        type: number
      sd2:
        type: number
      sdnn:
        type: number
      user_id:
        type: string
      vlf:
        type: number
    type: object
  models.LoginRequest:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: secret123
        type: string
    required:
    - email
    - password
    type: object
  models.LoginResponse:
    properties:
      expires_at:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.LogoutRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  models.PPGData:
    properties:
      timestamp:
        type: string
      value:
        type: number
    required:
    - timestamp
    - value
    type: object
  models.SensorData:
    properties:
      data:
        description: Heart rate value (e.g., beats per minute)
        items:
          $ref: '#/definitions/models.PPGData'
        type: array
      device_id:
        description: 'Optional: Identifier for the specific device'
        type: string
      sensor_data_id:
        description: Unique identifier for the sensor data
        type: string
      timestamp:
        description: Timestamp of the reading
        type: string
      user_id:
        description: Unique identifier for the user
        type: string
    required:
    - data
    - timestamp
    - user_id
    type: object
  models.UpdatePasswordRequest:
    properties:
      current_password:
        example: oldpassword123
        type: string
      new_password:
        example: newpassword123
        type: string
    required:
    - current_password
    - new_password
    type: object
  models.UpdateProfileRequest:
    properties:
      age:
        type: integer
      first_name:
        type: string
      gender:
        type: string
      height:
        type: number
      id:
        type: string
      last_name:
        type: string
      phone:
        description: Role      string  `json:"role"`
        type: string
      weight:
        type: number
    type: object
  models.User:
    properties:
      age:
        type: integer
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      height:
        type: number
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone:
        description: Role      string     `json:"role"`
        type: string
      updated_at:
        type: string
      weight:
        type: number
    type: object
  models.UserHRVAnalysisResponse:
    properties:
      analysis:
        items:
          $ref: '#/definitions/models.HRVAnalysisResult'
        type: array
      count:
        type: integer
    type: object
  models.UserRegisterModel:
    properties:
      confirm_password:
        minLength: 8
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - confirm_password
    - email
    - first_name
    - last_name
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an api gateway
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BeatSync API
  version: "1.0"
paths:
  /config:
    get:
      consumes:
      - application/json
      description: show service config data when the service environment set to debug
        mode
      operationId: get_config
      produces:
      - application/json
      responses:
        "200":
          description: Response data
          schema:
            allOf:
            - $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
            - properties:
                data:
                  $ref: '#/definitions/config.Config'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      summary: get config data on the debug mode
  /ping:
    get:
      consumes:
      - application/json
      description: this returns "pong" messsage to show service is working
      operationId: ping
      produces:
      - application/json
      responses:
        "200":
          description: Response data
          schema:
            allOf:
            - $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      summary: returns "pong" message
  /v1/analysis/{analysis_id}:
    get:
      consumes:
      - application/json
      description: Retrieve analysis data by its ID
      operationId: get-analysis-by-id
      parameters:
      - description: Analysis ID
        in: path
        name: analysis_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HRVAnalysisResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      security:
      - ApiKeyAuth: []
      summary: Get Analysis By ID
      tags:
      - data
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      operationId: login
      parameters:
      - description: login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      summary: Login User
      tags:
      - auth
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Invalidate user's JWT token
      operationId: logout
      parameters:
      - description: logout request
        in: body
        name: logout
        required: true
        schema:
          $ref: '#/definitions/models.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      security:
      - ApiKeyAuth: []
      summary: Logout User
      tags:
      - auth
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      operationId: register-user
      parameters:
      - description: user registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserRegisterModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      summary: Register User
      tags:
      - auth
  /v1/profile/{user_id}:
    get:
      consumes:
      - application/json
      description: Retrieve the profile of the authenticated user
      operationId: get-profile
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      security:
      - ApiKeyAuth: []
      summary: Get Profile
      tags:
      - profile
    put:
      consumes:
      - application/json
      description: Update authenticated user's profile
      operationId: update-profile
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: profile data
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/models.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      security:
      - ApiKeyAuth: []
      summary: Update User Profile
      tags:
      - profile
  /v1/profile/password:
    put:
      consumes:
      - application/json
      description: Update authenticated user's password
      operationId: update-password
      parameters:
      - description: password data
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/models.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      security:
      - ApiKeyAuth: []
      summary: Update User Password
      tags:
      - profile
  /v1/sensor-data:
    post:
      consumes:
      - application/json
      description: Save sensor data for analysis
      operationId: save-sensor-data
      parameters:
      - description: Sensor data
        in: body
        name: sensor_data
        required: true
        schema:
          $ref: '#/definitions/models.SensorData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      security:
      - ApiKeyAuth: []
      summary: Save Sensor Data
      tags:
      - data
  /v1/user-analysis:
    get:
      consumes:
      - application/json
      description: Retrieve all analysis data for a specific user within a date range
      operationId: get-user-analysis
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Start date in YYYY-MM-DD format
        in: query
        name: start_date
        type: string
      - description: End date in YYYY-MM-DD format
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserHRVAnalysisResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Ramazon1227_BeatSync_api_http.Response'
      security:
      - ApiKeyAuth: []
      summary: Get User Analysis
      tags:
      - data
securityDefinitions:
  ApiKeyAuth:
    description: Enter the token with Bearer prefix, e.g. "Bearer abcde12345"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
