version: '3.8'

services:
  app:
    image: golang:1.20
    container_name: go_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: go run main.go
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=beatsync
      - DOCKER_INFLUXDB_INIT_BUCKET=beatsync-bucket